### ISSUE TITLE
clickStage event does not return map coordinates

### ISSUE THREAD

**Issue by mgitkin-vz** [NeXt-UI/next-tutorials#3]
I've been able to successfully create an event handler for the 'clickStage' event. However, when I look through the returned event, I don't see any reference to the X Y coordinates for the mouse's position on the NeXt Map. The only coordinate information I am able to find is related to the webpage itself (ie. clientX, layerX, etc.)
 
Is there another event that I can listen for? Or are the map coordinates hidden somewhere special inside the returned event for 'clickStage'?
 
 
I've gone through the [NeXt API Documentation](https://communities.cisco.com/message/262747#262747) but I can't find anything that specifically mentions coordinates

**Comment by alwye** [comment]
Hi @mgitkin-vz 


Thanks for your interest in Next! Please check out [our example on Codepen](https://codepen.io/NEXTSUPPORT/pen/GNmNLe?editors=0010#0).

What you're looking for is in the line 18.

Have a nice day,
Al

**Comment by mgitkin-vz** [comment]
Thanks for the quick response @alwye. That's just what I was looking for.

I assumed that things would work similarly to Google Maps in that the exact value I was looking for would be in the event itself. I never thought to look for a method that would perform the translation for me.

I'll close my ticket on the Next forum and link to this answer.
