### ISSUE TITLE
documentation? 

### ISSUE THREAD

**Issue by dadamssg** [NeXt-UI/next-tutorials#6]
Is there any other documentation for the next-ui topology features other than this repo and the generated [api docs](https://github.com/NeXt-UI/next-bower/tree/master/doc)?

I know there's a lot of stuff that can be done with next-ui but I can't seem to find the documentation. 

I'm primarily interested in: 
- using different tooltips based on the node (where is `tooltipManagerConfig` documented?)

**Comment by alwye** [comment]
Hey @dadamssg.

I'm on a different team now, and have pinged the folks from the responsible team to reach out to you.

**Comment by dadamssg** [comment]
thanks, really appreciate that @alwye

**Comment by alwye** [comment]
@dadamssg presumably, the answer would be no 😞
